version: '3'

services:
  app:
    build:
      context: .
    container_name: app_container
    networks:
      - app_net
    expose:
      - "81"

  proxy:
    image: nginx:1.19.0
    container_name: proxy_container
    ports:
      - "80:8080"
    volumes:
      - ./nginx_proxy.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
